export default {
    FETCH_RESULTS: 'FETCH_RESULTS',
    FETCH_MOVIE_BY_ID: 'FETCH_MOVIE_BY_ID',
    CHANGE_SORT: 'CHANGE_SORT',
    CHANGE_FILTER: 'CHANGE_FILTER',
    UPDATE_SEARCH_INPUT: 'UPDATE_SEARCH_INPUT',
    UPDATE_SEARCH_RESULTS: 'UPDATE_SEARCH_RESULTS',
    SET_SELECTED_MOVIE: 'SET_SELECTED_MOVIE',
    RESET_SELECTED_MOVIE: 'RESET_SELECTED_MOVIE',
};
